GET_UNIT_PARENT_UNIT_IDS = """SELECT 
    rswf.WEEK_START_DATE, 
    rswf.UNIT_ID, 
    u.UNIT_NAME, 
    u.PARENT_UNIT_ID, 
    rswf.SALES, 
    rswf.WORKED_MINS, 
    rswf.ACTUAL_COST, 
    rswf.DAY_OFF_COUNT, 
    rswf.WLOAD_MINS, 
    rswf.SCHED_MINS_O
FROM RAR_STR_WEEK_F rswf, UNIT u
WHERE rswf.OWNER_ID = u.OWNER_ID  
    AND rswf.UNIT_SKEY = u.UNIT_SKEY  
    AND rswf.DEPT_SKEY = 0  
    AND rswf.WLOAD_MINS != 0  
    AND rswf.SCHED_MINS_O IS NOT NULL  
    AND rswf.WEEK_START_DATE >= VARCHAR_FORMAT(CURRENT DATE - 392 DAYS, 'YYYYMMDD')  
    AND rswf.WEEK_START_DATE <= VARCHAR_FORMAT(CURRENT DATE, 'YYYYMMDD')
ORDER BY  
    CASE WHEN rswf.WORKED_MINS IS NOT NULL AND rswf.WORKED_MINS != 0 THEN 1 ELSE 2 END,  
    CASE WHEN rswf.ACTUAL_COST IS NOT NULL AND rswf.ACTUAL_COST != 0 THEN 1 ELSE 2 END,  
    CASE WHEN rswf.SALES IS NOT NULL AND rswf.SALES != 0 THEN 1 ELSE 2 END,  
    CASE WHEN rswf.DAY_OFF_COUNT IS NOT NULL AND rswf.DAY_OFF_COUNT != 0 THEN 1 ELSE 2 END,  
    rswf.WEEK_START_DATE DESC 
FETCH FIRST 1 ROW ONLY"""
