about_us_title_locator = "about.title.about_us"
about_app_version_label_locator = "about.label.app_version"
about_build_version_locator = "about.label.build_version"
about_build_date_locator = "about.label.build_date"
about_branch_locator = "about.label.branch"
about_copyright_locator = "about.label.copyright"
about_licenses_locator = "about.button.licenses"
about_report_locator = "about.button.report"
about_logs_j_session_name_locator = "about.logs.j_session_name"
about_logs_detail_locator = "about.log.detail.semantic.label"
send_issue_mail_locator = "//*[@content-desc='Send']"
email_id_locator = "xpath=//android.view.ViewGroup[@resource-id='com.google.android.gm:id/peoplekit_autocomplete_chip_group']/android.widget.RelativeLayout"
workcloud_ess_log_attach_locator = "//*[contains(@content-desc,'Remove attachment')]"
