alternate_work_loc_add_title = "workloc.tabs.title.workloc"
alternate_work_loc_request_title = "workloc.tabs.title.requests"
alternate_work_loc_not_eligible_msg = "workloc.label.not_eligible"
alternate_work_loc_add_btn = "workloc.semantics.listing.add.button"
alternate_work_loc_add_window_title = "workloc.title.add"
alternate_work_loc_description = "workloc.label.description"
alternate_work_loc_start_date = "workloc.add.label.start_date"
alternate_work_loc_end_date = "workloc.add.label.end_date"
alternate_work_loc_note = "workloc.label.note"
alternate_work_loc_add_location = "workloc.add.label.add_location"
alternate_work_loc_req_submit = "workloc.add.label.submit.for.approval"
alternate_work_loc_select_title = "workloc.add.label.select_location"
alternate_work_loc_search = "workloc.label.search"
alternate_work_loc_selected = "workloc.add.label.selected"
alternate_work_loc_sel_loc_submit = "workloc.add.label.submit.for.approval"
alternate_work_loc_confirm_store = "workloc.add.label.done"
alternate_work_loc_status = "workloc.filter.label.status"
alternate_work_loc_requests_declined = "workloc.label.declined"
alternate_work_loc_requests_pending = "workloc.label.pending"
alternate_work_loc_requests_approved = "workloc.label.approved"
alternate_work_multi_loc_requests_partial_approved = "workloc.label.partial"
alternate_work_multi_loc_label = "workloc.semantics.listing.request.card.locations"
alternate_work_loc_req_details_window_title = "workloc.title.request_details"
alternate_work_loc_request_withdraw = "workloc.label.withdraw"
alternate_work_loc_request_withdraw_window_header = "workloc.title.withdraw"
alternate_work_loc_resubmit_for_approval = "workloc.add.label.resubmit.for.approval"
alternate_work_loc_date_range_label = "workloc.filter.label.date.range"
alternate_work_loc_request_filter = "workloc.semantics.listing.filter.request"
alternate_work_loc_search_approved_loc = "workloc.label.search"
alternate_work_loc_no_approved_loc = "workloc.label.no_approved_location"
alternate_work_loc_requests_tab = '//*[@content-desc[contains(., "{0}") and contains(., "Tab")]] | //*[@label[contains(., "{0}") and contains(., "Tab")]]'
# Native
confirm_add_button = '//*[@resource-id and substring-after(@resource-id, ":id/")="tvAddSelectedLocations"]'
search_button = '//*[@resource-id and substring-after(@resource-id, ":id/")="workLocationSearchEditText"]'
