BATCH_JOBS_MONITOR_QUEUE_TYPE_DRPDWN = "#queType"
BATCH_JOBS_MONITOR_SELECT_START_DATE = "#BTN_date1"
BATCH_JOBS_MONITOR_SELECT_END_DATE = "#BTN_date2"
BATCH_JOBS_MONITOR_SELECTED_DAY_IN_PICK_UP_CAL = "//table[@id='cal-datepicker']/tbody//td[@class=' day selected today' or @class=' day selected today weekend']"
BATCH_JOBS_MONITOR_DAY_IN_PICK_UP_CAL = "//table[@id='cal-datepicker']/tbody//td[contains(@class, 'day') and not(contains(@class, 'true')) and text()='{DAY}']"
BATCH_JOBS_MONITOR_CAL_PREV_MONTH_BTN = "//table[@id='cal-datepicker']//td[@id='prevMonth']"
BATCH_JOBS_MONITOR_CAL_NEXT_MONTH_BTN = "//table[@id='cal-datepicker']//td[@id='nextMonth']"
BATCH_JOBS_MONITOR_STATUS_DRPDWN = "#status"
BATCH_JOBS_MONITOR_APPLY_BTN = "td > span > input[value='Apply']"
# Environment-agnostic xpaths using parent div structure (works for both QA27 and BCF)
# Targets tbody with actual data rows (excludes header tbody with sr-row-hide rows)
BATCH_JOBS_MONITOR_FILTER_LIST_BLOCK = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]"
BATCH_JOBS_MONITOR_FILTER_LIST_RECORDS = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]//tr[not(contains(@class, 'sr-row-hide'))]"
BATCH_JOBS_MONITOR_CLEAR_BTN = "td > span > input[value='Clear']"
BATCH_JOBS_MONITOR_TBL_QUEUE_NAME = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]/tr[not(contains(@class, 'sr-row-hide'))][{BATCH_JOB_INDEX}]/td[normalize-space(text())='{QUEUE_TYPE_NAME}']"
BATCH_JOBS_MONITOR_TBL_STORE_NAME = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]/tr[not(contains(@class, 'sr-row-hide'))][{BATCH_JOB_INDEX}]/td[contains(normalize-space(text()),'{STORE_NAME}')]"
BATCH_JOBS_MONITOR_TBL_JOB_DESCRIPTION = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]/tr[not(contains(@class, 'sr-row-hide'))][{BATCH_JOB_INDEX}]/td[contains(normalize-space(text()),'{JOB_DESCRIPTION}')]"
BATCH_JOBS_MONITOR_WORKLOAD_TBL_JOB_DESCRIPTION = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]/tr[not(contains(@class, 'sr-row-hide'))][{BATCH_JOB_INDEX}]/td[contains(normalize-space(text()),'{JOB_DESCRIPTION}') and contains(normalize-space(text()),'{WEEK}')]"
BATCH_JOBS_MONITOR_TBL_JOB_STATUS = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]/tr[not(contains(@class, 'sr-row-hide'))][{BATCH_JOB_INDEX}]/td[normalize-space(text())='{JOB_STATUS}']"
BATCH_JOBS_MONITOR_TBL_JOB_PROGRESS = "//div[@id='batchJobListTableBody']//table/tbody[.//tr[not(contains(@class, 'sr-row-hide')) or @data-testid]]/tr[not(contains(@class, 'sr-row-hide'))][{BATCH_JOB_INDEX}]/td[normalize-space(text())='{JOB_PROGRESS}']"
BATCH_JOBS_MONITOR_SUBMITTED_BY_DRPDWN = "#submitBy"
BATCH_JOBS_MONITOR_DISP_PAGE_DRPDWN = "//select[@id='dispPage']"
BATCH_JOBS_MONITOR_DISP_PAGE_OPTION = "//select[@id='dispPage']/option"