PREDICTIVE_DRIVER_FORECAST_FORWARD_ARROW = ".ws-icon.ws-iconArrowDateRight"
PREDICTIVE_DRIVER_FORECAST_BACKWARD_ARROW = ".ws-icon.ws-iconArrowDateLeft"
PREDICTIVE_DRIVER_FORECAST_SELECTED_WEEK = "//span[@aria-label='{WEEK}']"
PREDICTIVE_DRIVER_FORECAST_TOTALS = "//span[text()='{DRIVER}']//parent::td//parent::tr//following-sibling::tr//td[text()='Actuals']//following-sibling::td//span[@class='ws-m-lr-4']"
PREDICTIVE_DRIVER_FORECAST_LOCATION_TYPE_DROPDOWN = "//select[@aria-label='Location Type']"
PREDICTIVE_DRIVER_FORECAST_LOCATION_DROPDOWN = "//button[@id='unitSkey-multi-sel-btn' and @role='combobox']"
PREDICTIVE_DRIVER_FORECAST_SEARCH_FIELD = "//input[@placeholder='Search']"
PREDICTIVE_DRIVER_FORECAST_STORE_NAME_INPUT = (
    "xpath=//div[normalize-space(@title)=normalize-space('{STORE_NAME}')]"
)
PREDICTIVE_DRIVER_FORECAST_CALENDER_ICON = "//span[@title='Calendar' and @role='button' and contains(@class, 'ws-iconCalendar')]"
PREDICTIVE_DRIVER_FORECAST_CALENDAR_MONTH_YEAR_HEADER = "//button[contains(@class, 'datePickerDayHeader')]"
PREDICTIVE_DRIVER_FORECAST_YEAR_BUTTON_BY_YEAR = "//button[contains(@aria-label, '{TARGET_YEAR}')]"
PREDICTIVE_DRIVER_FORECAST_YEAR_BUTTON_DYNAMIC = "//button[contains(@class, 'datePickerMonthHeader')]"
PREDICTIVE_DRIVER_FORECAST_YEAR_DIGITS_BY_LAST_TWO = "//button[contains(@class, 'btn-default')]//span[text()='{YEAR_LAST_2_DIGITS}']"
PREDICTIVE_DRIVER_FORECAST_MONTH_BUTTON_BY_NAME = "//button[@ng-click='monthYearChange(dt.date)' and contains(@class, 'btn-default')]//span[normalize-space()='{MONTH_NAME}']"
PREDICTIVE_DRIVER_FORECAST_DAY_BUTTON_BY_FORMATTED_DATE = "//button[contains(normalize-space(@aria-label), '{FORMATTED_DATE}')]"
PREDICTIVE_DRIVER_FORECAST_WEEK_NUMBER_BUTTON = "{DAY_LOCATOR}/preceding::td[@ng-if='showWeeks'][1]/button"
PREDICTIVE_DRIVER_FORECAST_CALENDAR_POP_UP = "//ul[@role='button']"
PREDICTIVE_DRIVER_FORECAST_INIT_BTN = "//button[normalize-space()='Initialize']"
