FREQ_PATTERN_ADVANCED_FILTER_ICON = "span.ws-iconFilter"
FREQ_PATTERN_ADVANCED_FILTER_APPLY_BTN = "a[ng-click*='applyFreqPatternFilter']"
FREQ_PATTERN_SORT_PREFERENCE_ICON = "span.ws-iconSort"
FREQ_PATTERN_SORT_PREFERENCE_OPTIONS = "div#sort-pref-option"
FREQ_PATTERN_ADD_FREQ_PATTERN_BTN = "span.ws-iconAdd"
FREQ_PATTERN_ADD_FREQ_PATTERN_SAVE_BTN = "button[ng-click*='saveFreqPatternDetails']"
FREQ_PATTERN_ADD_FREQ_PATTERN_PREVIOUS_BTN = "button[ng-click*='hideFreqPatternDetails']"
FREQ_PATTERN_ADD_FREQ_PATTERN_GREGORIAN_CAL_TAB = "div.ws-bottom-tab[ng-click*='GREGORIAN']"
FREQ_PATTERN_ADD_FREQ_PATTERN_GREGORIAN_CAL_SECTION = "div#rflxbspa-gregorian-calendar"
FREQ_PATTERN_ADD_FREQ_PATTERN_FISCAL_CAL_TAB = "div.ws-bottom-tab[ng-click*='FISCAL']"
FREQ_PATTERN_ADD_FREQ_PATTERN_FISCAL_CAL_SECTION = "div#rflxbspa-fiscal-calendar"
FREQ_PATTERN_ADD_FREQ_PATTERN_SPECIFIC_DATES_TAB = "div.ws-bottom-tab[ng-click*='SPECIFIC_DATE']"
FREQ_PATTERN_ADD_FREQ_PATTERN_SPECIFIC_DATES_SECTION = "div#rflxbspa-specific-dates"
FREQ_PATTERN_ADD_FREQ_PATTERN_LINKED_TO_PATTERN_TAB = "div.ws-bottom-tab[ng-click*='LINKED_TO_PATTERN']"
FREQ_PATTERN_ADD_FREQ_PATTERN_LINKED_TO_PATTERN_SECTION = "div#rflxbspa-linked-to-pattern"
FREQ_PATTERN_ADD_FREQ_PATTERN_APPLIES_TO_DATE_RANGE_TAB = "div.ws-bottom-tab[ng-click*='DATE_RANGE']"
FREQ_PATTERN_ADD_FREQ_PATTERN_APPLIES_TO_DATE_RANGE_SECTION = "div#rflxbspa-dateRange-calendar"
FREQ_PATTERN_FIRST_PATTERN_NAME = "td[ng-bind='freqPattern.patternName'] >> nth=0"
