CLOCK_IN_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="rBtnClockIn"] | //*[@name="Clock In"]'
CLOCK_OUT_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="rBtnClockOut"] | //*[@name="Clock Out"]'
NUM_PAD_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="manualProductKeyBtn{0}"] | //*[@name="Num Pad"]'
BADGE_ID_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="etBadgeId"] | //*[@name="BadgeID Value"]'
END_SESSION_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="tvEndSession"] | //*[@name="End Session"]'
EXTEND_SESSION_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="tvExtendSession"] | //*[@name="Extend Session"]'
ACTIVITY_CODE_NATIVE_CLOCK = '//*[@text="Activity Code"] | //*[@name="Activity Code"]'
SELECT_ACTIVITY_CODE_NATIVE_CLOCK = '//androidx.recyclerview.widget.RecyclerView/* | //XCUIElementTypeCell'
SUBMIT_PUNCH_ACTIVITY_CODE_NATIVE_CLOCK = '//*[@text="Submit Punch"] | //*[@name="Submit Punch"]'
SUBMIT_PUNCH_SUCCESSFULLY = '//*[@text="OK"] | //*[@name="OK"]'
MEAL_START_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="rBtnMealStart"] | //*[@name="Meal Start"]'
MEAL_END_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="rBtnMealEnd"] | //*[@name="Meal End"]'
BREAK_IN_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="rBtnBreakIn"] | //*[@name="Break In"]'
BREAK_OUT_BUTTON_NATIVE_CLOCK = '//*[@resource-id and substring-after(@resource-id, ":id/")="rBtnBreakOut"] | //*[@name="Break Out"]'
MANAGER_OVERRIDE_BUTTON_NATIVE_CLOCK = '//android.widget.ImageButton[contains(@resource-id,"ivManager")]'
TURN_OFF_OVERRIDE_BUTTON_NATIVE_CLOCK = '//android.view.View[contains(@resource-id,"rBtnTurnOffOverrideMode")]'