edit_store = '//*[@resource-id and substring-after(@resource-id, ":id/")="edit_store_text"] | //*[@name="Store Tap"]'
select_store= '//*[@resource-id and substring-after(@resource-id, ":id/")="dialogText" and @text="{0}"] | //*[@name="{0}"]'
edit_device_id = '//*[@resource-id and substring-after(@resource-id, ":id/")="edit_device_id_text"] | //*[@name="Device Id Value"]'
edit_device_location = '//*[@resource-id and substring-after(@resource-id, ":id/")="edit_device_location_text"] | //*[@name="Device Location Tap"]'
select_device_location= '//*[@resource-id and substring-after(@resource-id, ":id/")="dialogText" and @text="{0}"] | //*[@name="{0}"]'
edit_language = '//*[@resource-id and substring-after(@resource-id, ":id/")="edit_app_language_text"] | //*[@name="App Language Tap"]'
select_language = '//*[@resource-id and substring-after(@resource-id, ":id/")="dialogText" and @text="{0}"] | //*[@name="{0}"]'
enable_location_yes = '//*[@resource-id and substring-after(@resource-id, ":id/")="radio_yes"] | //*[@name="Yes"]'
enable_location_no = '//*[@resource-id and substring-after(@resource-id, ":id/")="radio_no"] | //*[@name="No"]'
exit_registration = '//*[@resource-id and substring-after(@resource-id, ":id/")="btn_exit"] | //*[@name="Exit Registration"]'
proceed_registration = '//*[@resource-id and substring-after(@resource-id, ":id/")="btn_proceed"] | //*[@name="Proceed"]'
finish_registration = '//*[@resource-id and substring-after(@resource-id, ":id/")="btn_finish"] | //*[@name="Finish & Continue"]'
accept_terms_condition = '//*[@resource-id and substring-after(@resource-id, ":id/")="cbOption"] | //*[@name="square"]'
continue_terms = '//*[@resource-id and substring-after(@resource-id, ":id/")="btnPrimary"] | //*[@name="Proceed"]'
close_registration_logout = '//*[@resource-id and substring-after(@resource-id, ":id/")="close_button"] | //*[@name="Cancel"]'