1800001201=Weekly Hours
1800001202=Working Hours
1800001203=Yrs. of Service
1800001204=Work Pattern
1800001205=Work Patterns
1800001206=Vacation Request
1800001207=Union
1800001208=Term Date
1800001209=Task Preference
1800001210=Terminate
1800001211=Student
1800001212=SSN
1800001213=Skill Level
1800001214=Break Entitlement
1800001215=Employment
1800001216=Date of Hire
1800001217=Date of birth must be entered
1800001218=First Name
1800001219=First Name must be entered
1800001220=Entitlement
1800001221=FT/PT
1800001222=Gender
1800001223=Gender must be selected
1800001224=Hire date
1800001225=Home
1800001226=Job Title
1800001227=Labor Cost/Hr
1800001228=Last Name
1800001229=Last Name must be entered
1800001230=Login ID
1800001231=Middle Name
1800001232=Minor
1800001233=New Hire
1800001234=New Hires
1800001235=Allow Login
1800001236=Employee
1800001237=Employee Type
1800001238=Performance Rating
1800001239=Should Employee be allowed to login to the system
1800001240=Skill
1800001241=Staff Group must be selected
1800001242=Employee Name
1800001243=Store must be entered
1800001244=Certifications
1800001245=Date of Birth
1800001246=Display Name
1800001247=Display Name must be entered
1800001248=Employee Id must be entered
1800001249=Age
1800001250=Cost/hr
1800001251=Employee Preference
1800001253=Type
1800001254=Associate ID
1800001255=Name Includes
1800001256=Employee Details
1800001257=Employee Information
1800001258=No Employee preference has been made
1800001259=Effective date must be entered
1800001260=School Calendar
1800001261=No task preference has been made
1800001262=Off Type
1800001263=End time must be selected
1800001264=End time must be greater than Start time
1800001265=No schools have been set for the user
1800001266=School Name
1800001267=Travel Time
1800001268=Mins
1800001269=in minutes
1800001270=State
1800001271=Zip Code
1800001272=Notes
1800001273=Home Phone
1800001274=IM Id
1800001275=Relationship
1800001276=Effective Date
1800001278=Certification
1800001279=Start date must be before End date
1800001280=Max Working Days
1800001281=End Date must be after effective Date
1800001282=Valid minimum normal daily hours must be entered
1800001283=Max
1800001284=Maximum Working Days must be selected
1800001285=Minimum normal daily hours must be entered
1800001286=Maximum normal daily hours should be greater than the Minimum normal daily hours
1800001287=Maximum normal weekly hours must be greater than Minimum Hours
1800001288=Labor cost/hr must be entered
1800001289=Add New School
1800001290=No time off requests received
1800001291=All Staffgroups
1800001292=Certified On
1800001293=Time
1800001294=Results
1800001295=Minor Employee
1800001296=Employee Status
1800001297=Show All
1800001298=Effective Date is after End Date
1800001299=Do you really want to delete this record
1800001300=Employee Name
1800001301=Add Time Off Details
1800001302=No Data to display for selected Date range
1800001303=Enter Date in Valid Format
1800001304=Start date is after End date
1800001305=Date of termination can not be before date of hire
1800001306=Do you really want to save this changes
1800001307=Reset Password
1800001308=Old Password
1800001309=New Password
1800001310=Re-enter Password
1800001311=Apply Seasonal Hours ?
1800012004=Dates overlap with existing date periods for co-worker .. please enter periods that do not overlap
1800012006=Cannot update records belonging to another store .. Please contact administrator
1800012010=Unable to delete records belonging to another store .. Please contact administrator
1800012011=Error setting Employee data
1800012012=Maximum Number of Leave Days Exceeded
1800012013=Valid Status must be selected
1800012014=Dates overlap with existing date periods .. please enter periods that do not overlap
1800012015=Unable to locate exiting status record .. Please contact administrator
1800012016=Unable to update Employee Status record .. Please contact administrator
1800012017=Unable to delete Employee Status record .. Please contact administrator
1800012018=No Status information Available
1800012019=Unable to locate existing co-worker record .. Please contact administrator
1800012020=Unable to update Employee co-worker preference record .. Please contact administrator
1800012021=Unable to add Employee co-worker preference record .. Please contact administrator
1800012022=Unable to locate existing workday preference record .. Please contact administrator
1800012023=Unable to delete Employee co-worker preference record .. Please contact administrator
1800012024=The new passwords do not match
1800012025=Incorrect old password
1800012026=Could not update password database
1800012027=Not eligible for leave
1800012028=Insufficient leave balance
1800012029=Unable to locate existing time off record .. Please contact administrator
1800012030=Unable to add Employee time off record .. Please contact administrator
1800012031=Unable to delete Employee time off record .. Please contact administrator
1800012032=Unable to update Employee time off record .. Please contact administrator
1800012034=Could not update User Permissions database
1800012035=Unable to add Employee Status record .. Please contact administrator
1800012036=Unable to add Staff Group record .. Please contact administrator
1800012037=Unable to add Employee record .. Please contact administrator
1800012038=Unable to add user record .. Please contact administrator
1800012039=A user already exists in the system with the same id .. Please use another user id and retry
1800012040=Employee with same Employee ID exists in the system .. please check
1800012041=Unable to update user record .. Please contact administrator
1800012042=Unable to delete Staff Group record.. Please contact administrator
1800012043=Unable to delete Status record.. Please contact administrator
1800012044=Unable to delete Available record.. Please contact administrator
1800012045=Unable to delete Award record.. Please contact administrator
1800012046=Unable to delete Contact record.. Please contact administrator
1800012049=Unable to delete Employee Preferences record.. Please contact administrator
1800012050=Unable to delete Task Preferences record.. Please contact administrator
1800012051=Unable to delete Work Day Preferences record.. Please contact administrator
1800012052=Unable to delete Employee record.. Please contact administrator
1800012053=Unable to delete TraceUser record.. Please contact administrator
1800012054=Unable to delete UserPermission record.. Please contact administrator
1800012055=There must be one HOME store for the Employee
1800012056=Effective Staff Group setting for Home Store is not currently defined
1800012057=Home for this Employee is already defined
1800012058=Error while adding School Calendar values
1800012059=Error while updating School Calendar values
1800012060=Error while deleting School Calendar values
1800012063=Unable to locate existing leave record .. Please contact administrator
1800012066=error while updating Employee status table
1800012070=Unable to update Employee record .. Please contact administrator
1800012071=Leave Request already exists for the Employee for the selected period
1800012072=Time Off request already exists for the Employee for the selected period
1800012073=Time Off request overlaps with the Leave Request for the Employee for the selected period
1800012074=Time Off request overlaps for the Employee for the selected period
1800012075=Maternity Leave
1800012076=Wage Details
1800012077=Release Employee To Store
1800012078=Release Employee to Department
1800012079=Release Employee to Staff Group
1800012080=Time Off Request
1800012081=Leave Request
1800012082=Entitlement
1800012083=Award Periods overlap with existing Awards
1800012084=Certification periods overlap with existing Certification
1800012085=Unexpected error occurred. Unable to Update Login Details for Employee
1800012086=Unable to Update Employee Details
1800012087=Date of Hire is after Wage Rate effective Date
1800012088=Holiday Hours Not Valid
1800012089=Unable to process Holiday Hours
1800012090=Holiday Hours for the week exceeds Minimum Contract Hours
1800012091=Please check the existing Time off/Leave Requests for the week
1800012092=Task Preference Report
1801011103=Results of
1801011205=Staffgroup
1801021101=Employee Roster Report
1801021201=Report Period
1801021205=Additional Filters
1801021207=All Active Employees
1801021208=All Minor Employees
1801021209=Terminated Employees
1801021210=Employee that have moved in / out of Staff Groups
1801021211=Employee that have had status changes
1801021212=None of the Above
1801021213=Select required columns
1801021217=Show All Departments
1801021218=Show All Staff Groups
1801021219=Show All Employee Status
1801021224=Date of birth
1801031102=Basic Details
1801031103=Login Detail
1801031301=Previous
1801031302=Save
1801041102=Contact Information
1801041103=Emergency Contact
1801041201=Email Id
1801041202=Alternate Email Id
1801041205=Mobile Phone
1801041206=Work Phone
1801041207=Alternate Phone
1801041208=Pager
1801041209=Street Address
1801041210=City
1801041213=Country
1801051102=Awards and Certifications
1801051103=Awards
1801051202=Award Name
1801051205=Certification Name
1801051301=Add Award
1801051302=Add Certification
1801061201=Award
1801061202=Validity From
1801061203=Award is valid for this store only
1801061204=Comments
1801061205=No Awards Received
1801061206=No Certifications received
1801061802=The date entry is not an acceptable format You can enter dates in the following formats mmddyyyy, mm/dd/yyyy, or mm-dd-yyyy
1801061803=Please select certification
1801061804=Comments cannot be longer than 256 characters
1801071101=Employment Information
1801071102=Employment Status
1801071103=Agreed Hours
1801081209=Years of Service
1801081211=Daily Hours
1801081212=Normal Hours/Week
1801081213=Overtime Hours
1801081214=Monthly Hours
1801081215=Yearly Hours
1801081216=Date Of Termination
1801081301=OK
1801081304=Rehire
1801081309=Contract Hours
1801081801=A valid Employee employment type must be selected
1801081802=A valid union code must be selected
1801081807=Valid minimum normal weekly hours must be entered
1801081809=Maximum OT hours must be greater than Minimum OT Hours
1801081810=Valid maximum OT hours must be entered
1801081811=Valid minimum OT hours must be entered
1801081812=Term Date must be greater than Hire Date
1801081813=Hire date must be entered
1801081814=A valid Employee status must be selected
1801081815=A valid Employee employment type must be selected
1801081816=Valid maximum normal daily hours must be entered
1801081819=Valid maximum normal weekly hours must be entered
1801091201=PIM Section
1801101211=Overtime Cost/Hr
1801101212=Additional Pay
1801101213=A valid Additional payment must be entered
1801101214=Employment
1801101803=End Date must be greater than Effective Date
1801101805=A valid job title must be selected
1801101806=A valid security group must be selected
1801101807=A valid department must be selected
1801101808=A valid skill level must be selected
1801101809=A valid performance rating must be selected
1801101811=A valid labor cost must be entered
1801101812=A valid overtime cost must be entered
1801101813=Selected Store cannot be set as home store
1801131101=Employee Availability
1801131202=Available Hours
1801131203=From
1801141102=Vacation Balance
1801141201=Category
1801141202=Balance as of
1801141206=Compensatory Off
1801141208=Paid Leave of Absence
1801141209=Personal
1801141210=Sick Leave
1801141211=Meeting/Training
1801141212=Unpaid Leave of Absence
1801141213=Vacation
1801151209=Reviewed by
1801161802=Time Off type must be selected
1801161803=Start time must be selected
1801161806=Valid reason must be selected
1801181201=Show Time Off Balance as of
1801181209=As Of
1801181803=A valid active task must be selected
1801201101=Preferences
1801201803=Employee Name must be selected
1801201804=Preference level must be selected
1801201806=End date should be after Effective Date
1801211225=Min
1801211805=Date of birth must be in the past
1801211808=Login ID must be specified
1801211811=Job Title must be selected
1801211812=Employee Primary Department must be selected
1801211813=Security group must be selected
1801211814=Date of hire must be entered
1801211815=Employment must be entered
1801211816=Minimum agreed hours must be selected
1801211820=Skill Level must be selected
1801211821=Performance Level must be selected
1801211822=Cost of Labor/hour must be specified
1801211823=Date of Birth is after Date of Hire
1801211828=Minor (Y/N) must be specified
1801211829=Password must contain at least 7 characters
1801211830=Enter chars for first 4 Characters and digits for the last 3 characters of the Password
1801211831=Individual Capacity
1801211832=Individual Capability
1801211833=School Travel Time
1801211834=School ID
1801211835=Individual capability must be entered
1801211836=Please enter Individual Capacity
1801211837=School travel time must be entered
1801211838=School id must be entered
1801221102=Time Off Details
1801221203=Date
1801231103=Time Off Details as of
1801241103=View By
1801241104=Certification Report
1801241201=All Stores
1801241204=Certified On or After
1801241205=Certificate
1801241208=Certificate Name
1801241209=Certificate On
1801241216=No Certification Records for Selected Filter Criteria
1801251101=Employee Preferences
1801251103=Employee Availability
1801251104=Colleague Preference
1801251105=Employee Availability: Employee Rota not set for this unit!!!
1801251107=Availability Type
1801251201=Select Employee
1801251202=All Employees
1801251203=Show this week
1801251204=Show this month
1801251205=Show for period
1801251207=Show Available Hours
1801251208=Show Colleague Preference
1801251209=Show Task Preference
1801251218=Task Name
1801251221=Colleague Name
1801261101=Validate Employee
1801261102=Employee Mismatch Report
1801261201=All Staffgroup
1801261207=Remarks
1801261208=Minimum Contracted Hours Not set
1801261209=Maximum Contracted Hours Not set
1801261210=Min Hours per day not set
1801261211=Max Hours per day not set
1801261212=Max working days per week not set
1801261213=No availability hours defined for
1801271101=Staff Calendar
1801271102=Show Base Availability
1801271103=Show Rejected Vacations
1801271104=Show Approved Vacations
1801271105=Show New Vacation Requests
1801271106=Approved Vacations
1801271107=Rejected Vacation requests
1801271108=New Vacation requests
1801271203=Monthly Agreed Hrs
1801271204=Monthly Agreed Ot Hrs
1801271205=Daily Agreed Hrs
1801271206=Daily Agreed Ot Hrs
1801271210=Unable to locate exiting Agreed Hours record .. Please contact administrator
1801271211=Unable to update Agreed Hours record .. Please contact administrator
1801271212=Unable to add Agreed Hours record .. Please contact administrator
1801271213=Unable to locate exiting Agreed Hours record .. Please contact administrator
1801271214=Unable to delete Employee Agreed Hours record .. Please contact administrator
1801271801=Max Monthly Agreed hours must be entered
1801271802=Maximum Monthly Agreed hours should be greater than the Minimum Monthly Agreed hours
1801271803=Maximum Monthly Agreed Ot hours should be greater than the Minimum Monthly Agreed Ot hours
1801271804=Maximum Daily Agreed hours should be greater than the Minimum Daily Agreed hours
1801271805=Maximum Daily Agreed Ot hours should be greater than the Minimum normal Daily Agreed Ot hours
1802011201=Message Board
1802011202=Messages posted by you
1802011203=Add/Edit Message
1802011204=Message Display Period
1802011205=Message By
1802011206=Visit
1802011207=No Messages To Display
1802011301=Create a Message
1802011801=Incorrect Display Date Range
1802011802=Valid Employee must be selected
1802011803=Break Entitlement must be specified
1802011804=Home Staff Group
1802011805=Employee Availability Template
1802011806=Email
1802011807=SMS
1802011808=Both
1802011809=None
1802011810=Unable to add Available record .. Please contact administrator
1802011811=Unable to add Contact record .. Please contact administrator
1802011812=Release Employee to Territory
1802011813=Unable to add staff Status record .. Duplicate/Invalid data entry
1802011814=HRCI Audits
1802011815=Employee Template
1802011816=Release Employee to Staff
1802011817=Team Member Productivity
1802011818=Hours to Goal
1802011819=This attachment already exists for the employee
1802011820=User is not authorised to perform this action
1802011821=Employee Picture size exceeded
1802011822=Date of Hire is after End Date
1802011823=End Date
1802011824=Please select State
1802011825=Please select Country
1802011826=Please enter Zip Code
1802011827=Cannot add Logical Staff Group belonging to the same Staff group in the overlaping period. Please enter periods that do not overlap
1802011828=Cannot add same Staff group in the overlaping period. Please enter periods that do not overlap
1802011830=Please Select
1802011831=Term date must be greater than Selected Date
1802011832=Alternate work location request
1802011833=Out of Office/Delegation
1802011834=Reporting Hierarchy
1802011835=Reporting Manager
1802011836=New hire functionality is meant to facilitate only Store level users, Please login as Store Manager
1802011837=Incorrect effective date has been selected
1802011838=Incorrect end date has been selected
1802011839=Department type must be selected
1802011840=Department type
1802011841=Non Home
1802011842=Shift Patterns For Unit
1802011844=Hours Allocation
