ALT_WORK_LOCATION_TAB = '1000000001281'
ALT_WORK_LOCATION_STATUS_APPROVED_KEY = '1000000000250'
ALT_WORK_LOCATION_STATUS_DECLINED_KEY = '1000000000252'
ALT_WORK_LOCATION_STATUS_NOT_REVIEWED_KEY = '1000000000253'
ALT_WORK_LOCATION_DELETE_KEY = '1000000000084'
ALT_WORK_LOCATION_UPDATE_KEY = '1000000001140'
ALT_WORK_LOCATION_REQUEST_DESCRIPTION_FIELD = '{0}//android.widget.TextView[contains(@resource-id,"decription_tv") and @text="{1}"]'
ALT_WORK_LOCATION_REQUEST_STORE_FIELD = '{0}//android.widget.TextView[contains(@resource-id,"location_tv") and @text="{1}"]'
ALT_WORK_LOCATION_REQUEST_DATE_RANGE_FIELD = '{0}//android.widget.TextView[contains(@resource-id,"effective_dates_tv") and @text="{1}"]'
ALT_WORK_LOCATION_REQUEST_STATUS_FIELD = '{0}//android.widget.TextView[contains(@resource-id,"dest_status_tv") and @text="{1}"]'
ALT_WORK_LOCATION_REQUEST_LIST_ITEM_BY_STORE_DATE_STATUS = '//androidx.recyclerview.widget.RecyclerView[contains(@resource-id,"alternate_work_loc_recycler")]//android.view.ViewGroup[.//android.widget.TextView[contains(@text, "{0}")] and .//android.widget.TextView[@text="{1}"] and .//android.widget.TextView[@text="{2}"]]'
ROSTER_MORE_OPTIONS_ALT_WORK_LOCATION = '//android.widget.Button[@text="{0}"]'
ALT_WORK_LOCATION_TAB_HEADER = '//android.widget.TextView[contains(@resource-id,"tv_title") and @text="{0}"]'
ALT_WORK_LOCATION_EDIT_STATUS = '//android.widget.EditText[contains(@resource-id,"status_tv")]'
ALT_WORK_LOCATION_STATUS_APPROVED = '//android.widget.TextView[@text="{0}"]'
ALT_WORK_LOCATION_STATUS_DECLINED = '//android.widget.TextView[@text="{0}"]'
ALT_WORK_LOCATION_STATUS_NOT_REVIEWED = '//android.widget.TextView[@text="{0}"]'
ALT_WORK_LOCATION_UPDATE_STATUS = '//android.widget.Button[contains(@text,"{0}")]'
ALT_WORK_LOCATION_DELETE_BUTTON = '//android.widget.Button[contains(@text,"{0}")]'
ALT_WORK_LOCATION_CANCEL_DETAILS = '//android.widget.TextView[contains(@resource-id,"btn_close")]'
ALT_WORK_LOCATION_CURRENT_APPROVED = '//android.widget.EditText[@text="{0}"]'
ALT_WORK_LOCATION_WITHDRAW = '//android.widget.Button[contains(@resource-id,"btn_withdraw")]'
ALT_WORK_LOCATION_ADD_BTN = '//android.widget.ImageButton[contains(@resource-id,"btn_add")]'
ALT_WORK_LOCATION_DESCRIPTION = '//android.widget.EditText[contains(@resource-id,"et_desc")]'
ALT_WORK_LOCATION_ADD_LOCATION = '//android.widget.EditText[contains(@resource-id,"et_unit")]'
ALT_WORK_LOCATION_STATUS = '//android.widget.EditText[contains(@resource-id,"et_status")]'
ALT_WORK_LOCATION_START_DATE = '//android.widget.EditText[contains(@resource-id,"et_effDate")]'
ALT_WORK_LOCATION_END_DATE = '//android.widget.EditText[contains(@resource-id,"et_endDate")]'
ALT_WORK_LOCATION_COMMENT = '//android.widget.EditText[contains(@resource-id,"et_comment")]'
ALT_WORK_LOCATION_SELECT_TITLE = '//android.widget.TextView[@text="Select Stores"]'
ALT_WORK_LOCATION_SEARCH = '//android.widget.EditText[contains(@resource-id,"et_search")]'
ALT_WORK_LOCATION_DONE = '//android.widget.Button[contains(@resource-id,"btn_done")]'
ALT_WORK_LOCATION_SUBMIT_BTN ='//android.widget.TextView[contains(@resource-id,"btn_submit")]'
ALT_WORK_LOCATION_TAB = '1000000001281'
ROSTER_MORE_OPTIONS_ALTERNATE_WORK_LOCATION = '//android.widget.Button[@text="{0}"]'
ALT_WORK_LOCATION_TAB_HEADER = '//android.widget.TextView[contains(@resource-id,"tv_title") and @text="{0}"]'
ALT_WORK_LOCATION_EDIT_STATUS = '//android.widget.EditText[contains(@resource-id,"status_tv")]'
ALT_WORK_LOCATION_STATUS_APPROVED = '//android.widget.TextView[@text="{0}"]'
ALT_WORK_LOCATION_STATUS_DECLINED = '//android.widget.TextView[@text="{0}"]'
ALT_WORK_LOCATION_STATUS_NOT_REVIEWED = '//android.widget.TextView[@text="{0}"]'
ALT_WORK_LOCATION_UPDATE_STATUS = '//android.widget.Button[contains(@text,"{0}")]'
ALT_WORK_LOCATION_DELETE_BUTTON = '//android.widget.Button[contains(@text,"{0}")]'
ALT_WORK_LOCATION_CANCEL_DETAILS = '//android.widget.TextView[contains(@resource-id,"btn_close")]'
ALT_WORK_LOCATION_CURRENT_APPROVED = '//android.widget.EditText[@text="{0}"]'
ALT_WORK_LOCATION_WITHDRAW = '//android.widget.Button[contains(@resource-id,"btn_withdraw")]'
ALT_WORK_LOCATION_BACK_BTN = '//android.widget.ImageButton[contains(@resource-id,"ib_back_btn")]'