ASSOCIATE_FILTER_ICON = "//android.widget.ImageButton[contains(@resource-id,'btn_associate_filter')]"
ASSOCIATE_STATUS_ARROW = "//android.widget.TextView[contains(@resource-id,'statusArrowImg')]"
APPLY_FILTER_BUTTON = "//android.widget.TextView[contains(@resource-id,'tv_filter_save')]"
ACTIVE_STATUS = '//android.widget.TextView[contains(@resource-id,"dropDownTv") and @text="{0}"]'
ACTIVE_STATUS_SELECTED_ICON = '//android.widget.ImageView[contains(@resource-id,"statusSelectionCloseImg")]'
SEARCH_ICON = "//android.widget.ImageButton[contains(@resource-id,'btn_associate_search')]"
SEARCH_FIELD = "//android.widget.EditText[contains(@resource-id,'edt_associate_search')]"
SEARCHED_ASSOCIATE = '//android.widget.TextView[contains(@resource-id,"TV_associate")] | //android.widget.TextView[contains(@resource-id,"associate_name")] | //XCUIElementTypeStaticText[@name="{0}"]'
ASSOCIATE_ROSTER_PAGE_ASSOCIATE_ID = '//android.widget.EditText[contains(@resource-id,"userIdTv")]'
DYNAMIC_ASSOCIATE_ID = '//android.widget.EditText[contains(@resource-id,"userIdTv") and @text="{0}"]'
ASSOCIATE_ROSTER_PAGE_LAST_NAME = '//android.widget.EditText[contains(@resource-id,"lastNameTv")]'
ASSOCIATE_DYNAMIC_LAST_NAME = '//android.widget.EditText[contains(@resource-id,"lastNameTv") and @text="{0}"]'
ASSOCIATE_ROSTER_PAGE_FIRST_NAME = '//android.widget.EditText[contains(@resource-id,"firstNameTv")]'
ASSOCIATE_DYNAMIC_FIRST_NAME = '//android.widget.EditText[contains(@resource-id,"firstNameTv") and @text="{0}"]'
ASSOCIATE_ROSTER_PAGE_DISPLAY_NAME = '//android.widget.EditText[contains(@resource-id,"displayNameTv")]'
ASSOCIATE_DYNAMIC_DISPLAY_NAME = '//android.widget.EditText[contains(@resource-id,"displayNameTv") and @text="{0}"]'
ASSOCIATE_ROSTER_PAGE_GENDER = '//android.widget.TextView[contains(@resource-id,"genderTv")]'
ASSOCIATE_DYNAMIC_GENDER = '//android.widget.TextView[contains(@resource-id,"genderTv") and @text="{0}"]'
ASSOCIATE_ROSTER_PAGE_EDIT_ICON = '//android.widget.ImageButton[contains(@resource-id,"btn_edit")]'
ASSOCIATE_ROSTER_PAGE_SAVE_BUTTON = '//android.widget.TextView[contains(@resource-id,"btn_save")]'
ASSOCIATE_ROSTER_PAGE_NOTIFICATION_MESSAGE = '//android.widget.TextView[contains(@resource-id,"snackBarTitle")]'
ASSOCIATE_ROSTER_DYNAMIC_NOTIFICATION = '//android.widget.TextView[contains(@resource-id,"snackBarTitle") and contains(@text, "{0}")]'
ASSOCIATE_ROSTER_PAGE_HEADER_PROFILE_TAB = '1000000000021'
ASSOCIATE_ROSTER_PAGE_HEADER_CONTACT_TAB = '1000000000708'
ASSOCIATE_ROSTER_PAGE_CONTACT_TAB_CONTACT_INFO = '//android.widget.TextView[contains(@resource-id,"btnContactInfo")]'
ASSOCIATE_ROSTER_PAGE_CONTACT_INFO_MOBILE_PHONE = '//android.widget.EditText[contains(@resource-id,"contactMobilePhoneTV")]'
ROSTER_MORE_OPTIONS_ICON = '//android.widget.ImageButton[contains(@resource-id,"ibMoreTabs")]'
ROSTER_MORE_OPTIONS_AVAILABILITY = '//android.widget.Button[@text="{0}"]'
ASSOCIATE_SCROLL_VIEW_CONTAINER = '//android.widget.ScrollView[contains(@resource-id,"scrollView2")]'

# Availability tabs
AVAILABILITY_TAB_HEADER = '//android.widget.TextView[contains(@resource-id,"tv_title") and @text="{0}"]'
ADD_AVAILABILITY_BUTTON = '//android.widget.ImageButton[contains(@resource-id,"btn_add")]'
REDIO_BUTTON_PERMANENT= '//android.widget.RadioButton[contains(@resource-id,"r_perm")]'
REDIO_BUTTON_TEMPORARY= '//android.widget.RadioButton[contains(@resource-id,"r_temp")]'
START_DATE_LOCATOR = '//android.widget.TextView[contains(@resource-id,"tvEffectiveDate")]'
REASON_DROPDOWN = '//android.widget.TextView[contains(@resource-id,"tvReason")]'
STATUS_DROPDOWN = '//android.widget.TextView[contains(@resource-id,"tvStatus")]'
AVAILABLE_ALL_WEEK_TOGGLE = '//android.widget.Switch[contains(@resource-id,"all_days_available_toggle")]'
TOTAL_ROTATIONS_DROPDOWN = '//android.widget.TextView[contains(@resource-id,"noOfRotationsEdt")]'
ROTATION_LIST_ITEM_LOCATOR = '//androidx.recyclerview.widget.RecyclerView[contains(@resource-id,":id/reasons_recycler_view")]/android.widget.RelativeLayout[{0}]'
ROTATION_NUMBER_TAB_LOCATOR = '//android.widget.TextView[contains(@resource-id,"btn") and contains(@resource-id,"Rotation") and @text="{0}"]'
NON_WORKING_DAY_TOGGLE_LOCATOR = '//android.widget.CheckBox[contains(@resource-id,"cbDay{0}")]'
EDIT_DETAILS_BUTTON = '//android.widget.ImageButton[contains(@resource-id,"ib_edit_button")]'
AVAILABILITY_TIMING_CONTAINER = '//android.widget.LinearLayout[contains(@resource-id,"id/ll_main")]'
# Add availability window locators
AVAIL_BASE_TIMING_LOCATOR = '//android.widget.TextView[contains(@resource-id,"tvDay{0}Base1")]'
AVAIL_PREF_TIMING_LOCATOR = '//android.widget.TextView[contains(@resource-id,"tvDay{0}Pref1")]'
AVAIL_ONCALL_TIMING_LOCATOR = '//android.widget.TextView[contains(@resource-id,"tvDay{0}OnCall1")]'
AVAILABLE_ALL_DAY_TOGGLE = '//android.widget.Switch[contains(@resource-id,"all_day_toggle")]'
AVAILABLE_ALL_DAY_TOGGLE_WITH_INDEX = 'xpath=(//android.widget.Switch[contains(@resource-id,"all_day_toggle")])[last()]'
START_TIME_INPUT= '//android.widget.EditText[contains(@resource-id,"tv_start_time")]'
START_TIME_INPUT_WITH_INDEX= 'xpath=(//android.widget.EditText[contains(@resource-id,"tv_start_time")])[last()]'
END_TIME_INPUT= '//android.widget.EditText[contains(@resource-id,"tv_end_time")]'
END_TIME_INPUT_WITH_INDEX= 'xpath=(//android.widget.EditText[contains(@resource-id,"tv_end_time")])[last()]'
AVAIL_APPLICABLE_DAYS = '//android.widget.TextView[contains(@resource-id,"{0}")]'
AVAIL_APPLICABLE_DAYS_WITH_INDEX = 'xpath=(//android.widget.TextView[contains(@resource-id,"{0}")])[last()]'
AVAIL_WINDOW_ADD_BUTTON = '//android.widget.ImageButton[contains(@resource-id,"btn_add")]'
TIMING_DONE_BUTTON = '//android.widget.TextView[contains(@resource-id,"btn_submit")]'
AVAILABILITY_SUBMIT = '//android.widget.TextView[contains(@resource-id,"btn_submit")]'
AVAILABILITY_SAVE = '//android.widget.TextView[contains(@resource-id,"save_button")]'

# Availability list page
AVAILABILITY_LIST_ITEM_SEMANTIC	= '//android.view.ViewGroup[contains(normalize-space(@content-desc),"{0} - {1}") and contains(normalize-space(@content-desc),"{2}")]'

# Availability details page
AVAILABILITY_DETAILS_PERMANENT = '//android.widget.RadioButton[contains(@resource-id,"r_perm") and @checked="true"]'
AVAILABILITY_DETAILS_TEMPORARY = '//android.widget.RadioButton[contains(@resource-id,"r_temp") and @checked="true"]'
AVAILABILITY_DETAILS_START_DATE = '//android.widget.EditText[contains(@resource-id,"edtAvailStartWeek") and contains(@text,"{0}")]'
AVAILABILITY_DETAILS_END_DATE = '//android.widget.EditText[contains(@resource-id,"edtAvailEndWeek") and contains(@text,"{0}")]'
AVAILABILITY_DETAILS_REASON = '//android.widget.EditText[contains(@resource-id,"availReasonTV") and contains(@text,"{0}")]'
AVAILABILITY_DETAILS_STATUS = '//android.widget.EditText[contains(@resource-id,"availStatusTV") and contains(@text,"{0}")]'
AVAILABILITY_DETAILS_AVAILABLE_ALL_WEEK = '//android.widget.Switch[contains(@resource-id,"all_days_available_toggle") and @checked="true"]'
AVAILABILITY_DETAILS_ROTATION_NUMBER = '//android.widget.TextView[contains(@resource-id,"btnFirstRotation") and contains(@text,"{0}")]'
AVAILABILITY_DETAILS_NON_WORKING_DAY = '//android.widget.CheckBox[contains(@resource-id,"cbDay{0}") and @checked="true"]'
AVAILABILITY_DETAILS_TIMING = '//android.widget.TextView[contains(@resource-id,"tvDay{0}Base") and contains(@text,"{1}")]'
DELETE_AVAILABILITY_BUTTON = '//android.widget.Button[contains(@resource-id,"btn_delete")]'
DELETE_CONFIRM_BUTTON = '//android.widget.Button[contains(@resource-id,"button1")]'