SM_MY_STORE_ADD_OPEN_SHIFT_BTN = '//android.widget.ImageButton[contains(@resource-id,"btn_add_opneShift")]'
SM_MY_STORE_OK_ACTION_BTN = '//android.widget.Button[contains(@resource-id,"actionButton")]'
SM_OPEN_SHIFT_CALENDAR_NAVIGATION = '//*[contains(@resource-id,"et_cal_date")]'
SM_OPEN_SHIFT_SELECT_STAFF_GROUP = '//android.widget.LinearLayout[contains(@resource-id,"rl_contain_StaffGroup")]'
SM_OPEN_SHIFT_OPTION_IN_STAFF_GROUP_LIST = '//android.widget.TextView[@text="{0}"]'
SM_OPEN_SHIFT_SELECT_START_TIME = '//android.widget.TextView[contains(@resource-id,"et_start_time")]'
SM_OPEN_SHIFT_SELECT_END_TIME = '//android.widget.EditText[contains(@resource-id,"et_end_time")]'
SM_OPEN_SHIFT_SELECT_TASK = '//android.widget.EditText[contains(@resource-id,"et_task")]'
SM_OPEN_SHIFT_TOGGLE_KEYBOARD = '//android.widget.ImageButton[contains(@resource-id,"toggle_mode")]'
SM_OPEN_SHIFT_HOUR_INPUT = '//android.widget.EditText[contains(@resource-id,"input_hour")]'
SM_OPEN_SHIFT_MINUTE_INPUT = '//android.widget.EditText[contains(@resource-id,"input_minute")]'
SM_OPEN_SHIFT_AM_PM_SELECT = '//android.widget.Spinner[contains(@resource-id,"am_pm_spinner")]'
SM_OPEN_SHIFT_AM_VALUE_SELECT = '//*[@text="AM"]'
SM_OPEN_SHIFT_PM_VALUE_SELECT = '//*[@text="PM"]'
SM_OPEN_SHIFT_TIME_DIALOG_OK_BTN = '//android.widget.Button[contains(@resource-id,"button1")]'
SM_OPEN_SHIFT_SAVE_SHIFT_BTN = '//android.widget.TextView[contains(@resource-id,"btn_save_shift")]'
SM_OPEN_SHIFT_OPTION_IN_TASK_LIST = '//android.widget.TextView[contains(@resource-id,"tv_staffGrpName") and @text="{0}"]'
SM_OPEN_SHIFT_SAVE_OPTION = '//android.widget.LinearLayout[contains(@resource-id,"positiveButtonSpace")]//android.widget.Button[contains(@text,"{0}")]'
SM_OPEN_SHIFT_NOTIFICATION_MESSAGE = '//android.widget.TextView[contains(@resource-id,"snackBarTitle")][contains(@text,"{0}")]'
SM_OPEN_SHIFT_GENERIC_NOTIFICATION = '//android.widget.TextView[contains(@resource-id,"snackBarTitle")]'
SM_OPEN_SHIFT_REQUEST = 'xpath=(//android.widget.TextView[contains(@text,"{0}")]//parent::android.widget.LinearLayout//following-sibling::*//*[contains(@text,"{1}")]//following-sibling::*//*[contains(@resource-id,"tv_shiftTimings") and contains(@text,"{2}")])[1]'
SM_OPEN_SHIFT_TAB = '//android.widget.TextView[contains(@resource-id,"tv_title") and @text="{0}"]'
SM_OPEN_SHIFT_ASSIGN_MY_STORE_BTN = '//android.widget.Button[contains(@resource-id,"myStoreReassignBtn")]'
SM_OPEN_SHIFT_ASSOCIATE_OPTION = '//android.widget.TextView[contains(@resource-id,"tv_assign_name") and @text="{0}"]'
SM_OPEN_SHIFT_ASSIGN_SHIFT = '//android.widget.LinearLayout[contains(@resource-id,"positiveButtonSpace")]//android.widget.Button[contains(@text,"{0}")]'
SM_OPEN_SHIFT_DELETE_OPEN_SHIFT_BTN = '//android.widget.Button[contains(@resource-id,"btn_delete_shift")]'
SM_OPEN_SHIFT_DIALOG_CONFIRM_BTN = '//android.widget.Button[contains(@resource-id,"btnPositive")]'
SM_OPEN_SHIFT_MORE_BUTTON = '//android.widget.ImageButton[contains(@resource-id,"ibMoreTabs")]'
SM_OPEN_SHIFT_SEARCH_ICON = '//android.widget.ImageButton[contains(@resource-id,"ib_search")]'
SM_OPEN_SHIFT_SEARCH_ASSOCIATE_FIELD = '//android.widget.EditText[contains(@resource-id,"edt_search")]'

# semantics keys
SM_OPEN_SHIFT_SAVE_DO_NOT_APPLY_MEAL_BREAK = '1000000001257'
SM_OPEN_SHIFT_ADDED_MESSAGE = '1000000001478'
SM_OPEN_SHIFT_ASSIGN_TEXT = '1000000000116'