RFP_UPLOAD_PAGE_DATATYPE_DROPDOWN = "//select[@id='selectUpload']"
RFP_UPLOAD_PAGE_FILE_NAME_TXT = "//input[@id='file_name']"
RFP_UPLOAD_PAGE_FILE_UPLOAD_BTN = "//input[@id='uploadBtn']"
RFP_UPLOAD_PAGE_PREVIOUS_BTN = "//input[@id='btnPrevious']"
RFP_LOGS_PAGE_DATATYPE_DROPDOWN = "//select[@id='selectUploadDataType']"
RFP_LOGS_PAGE_LOG_FILE_DROPDOWN = "//select[@class='ipfield']"
RFP_LOGS_PAGE_VALIDATE_AND_SUBMIT_BTN = "//input[@id='btnValidateAndSubmit']"
RFP_UPLOAD_PAGE_FILE_UPLOAD_LBL = "//tr/td[@class='tblrow' and @align='left' and contains(text(), ':')]"
RFP_UPLOAD_PAGE_SCHEDULE_REGEN_DROPDOWN = "//select[@id='regenOption']"