STORE_SCHEDULE_PAGE_NEXT_WEEK_ICON = "//span[@aria-label='Next Week']"
STORE_SCHEDULE_PAGE_SHIFT_PRESENCE = "(//span[contains(@aria-label, 'Shift')])[1]"
STORE_SCHEDULE_PAGE_ASSOCIATE_DAY_SHIFT_CONTAINER = "//div[contains(@class,'employeeName')][contains(text(),'{ASSOCIATE_NAME}')]/parent::td//following-sibling::td[{DAY}]//span[@role='cell']"
STORE_SCHEDULE_PAGE_NOT_PUBLISHED_MSG = "//div[contains(@class,'scheduledShiftContainerBody')]//span[contains(text(),'not published')]"
STORE_SCHEDULE_PAGE_SPINNER = "//div[contains(@class,'rfx-spinner')]"
STORE_SCHEDULE_PAGE_WEEK_LABEL = "//span[contains(@class,'weekDateLabel')]"
STORE_SCHEDULE_PAGE_WEEK_DROPDOWN = "//ul[@class]/li/div[contains(@class, 'datepicker')]"
STORE_SCHEDULE_PAGE_PRINT_ICON = "#essQLaunchPrintButton"
STORE_SCHEDULE_PAGE_PRINT_POPUP = "//div[contains(@ng-if, 'showPrintUserActionsButtonClick')]"
STORE_SCHEDULE_PAGE_FILTER_ICON = "#filterEmployees"
STORE_SCHEDULE_PAGE_FILTER_PANEL = "//div[@id='empFilterPanel' and @style]"
STORE_SCHEDULE_PAGE_DISPLAY_PREF_ICON = "#displayPrefIcon"
STORE_SCHEDULE_PAGE_DISPLAY_PREF_PANEL = "#essScheduleDisplayConfiguration"
STORE_SCHEDULE_PAGE_LEGEND_ICON = "#essQLaunchLegendButton"
STORE_SCHEDULE_PAGE_LEGEND_PANEL = "#legendDialog"