GENERATE_WEEK_PLAN_FORECAST_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/GENERATE_FC/**"
GENERATE_WORKLOAD_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/GENERATE_WL/**"
GENERATE_OPTIMIZED_SCHEDULE_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/GENERATE_SC/**"
PUBLISH_SCHEDULE_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/PUBLISH_SC/**"
UNPUBLISH_SCHEDULE_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/UNPUBLISH_SC/**"
DELETE_SCHEDULE_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/DELETE_SC/**"
DELETE_SCHEDULE_AND_WORKLOAD_API_REGEX = "**/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/DELETE_WL/**"
GENERATE_WORKLOAD_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/workload/generate/{STORE}/{WEEK_START_DATE}.json"
GENERATE_FORECAST_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/GENERATE_FC/{STORE}/{WEEK_START_DATE}/NONE.json"
GENERATE_SCHEDULE_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/GENERATE_SC/{STORE}/{WEEK_START_DATE}/NONE.json"
DELETE_SCHEDULE_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/DELETE_SC/{STORE}/{WEEK_START_DATE}/{SCHEDULE_ITERATION}.json"
DELETE_WORKLOAD_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/DELETE_WL/{STORE}/{WEEK_START_DATE}/NONE.json"
UNPUBLISH_SCHEDULE_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/UNPUBLISH_SC/{STORE}/{WEEK_START_DATE}/{SCHEDULE_ITERATION}.json"
GET_FISCAL_WEEK_NUMBER_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/mobile/schedule/rosom/mobileschedulecontext/new/MGR/IPAD.json"
GET_SHIFT_ID_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/mobile/schedule/core/mobileweeklyschedulecontext/{WEEK_START_DATE}/false.json"
PUBLISH_SCHEDULE_MOBILE_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/mobile/schedule/core/advanced/publish/{STORE}/{WEEK_START_DATE}/{USER_TYPE}.json"
UNALLOCATE_SHIFT_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/shift/advanced/actions/unallocate/{GEN_SHIFT_ID}/{STORE}/{SHIFT_SEQ_NO}/0/1440/false.json"
DELETE_OPEN_SHIFT_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/openshift/basic/{STORE}/{GEN_SHIFT_ID}/{SHIFT_SEQ_NO}/0/1440.json"
ADD_SHIFT_API_TEMPLATE = "{ENVIRONMENT}/controller/rws/weekplan/web/schedule/shift/basic/{STORE}/{GEN_SHIFT_ID}/0/1440/false.json"
WIP_SERVLET_URL="{BASE_URL}/servlet/PublishSchedules?unitId={UNIT_ID}"
GET_UNIT_STATE_MAP_API="{BASE_URL}/controller/rws/weekplan/web/common/unit/map/getUnitStateMap/{UNIT_ID}/{WEEK_START_DATE}.json"
UNLOCK_SCHEDULE_API_TEMPLATE = "{BASE_URL}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/UNLOCK_SCHEDULE/{STORE}/{WEEK_START_DATE}/{SCHEDULE_ITERATION}.json"
LOCK_SCHEDULE_API_TEMPLATE = "{BASE_URL}/controller/rws/weekplan/web/schedule/core/advanced/executeplanstatusevent/LOCK_SCHEDULE/{STORE}/{WEEK_START_DATE}/{SCHEDULE_ITERATION}.json"
GET_GEN_SHIFT_ID_API_TEMPLATE = "{BASE_URL}/controller/ess/core/latestgenshift/{STORE}/{WEEK_START_DATE}.json"
DELETE_WEEK_PLAN_SERVLET_URL = "{BASE_URL}/servlet/DeleteWeeklyPlanData?UNIT_ID={UNIT_ID}&DATE_SKEY={WEEK_START_DATE}"