*** Settings ***
Documentation       Week 0, Week 1 & Week 2 - SM1_STORE2 Schedule Suite
...
...                 **PURPOSE:**
...                 This suite consolidates all BATTC test cases that require Week 0, Week 1, and Week 2 schedule data for Store2.
...                 All tests in this suite use the same week setup, enabling efficient parallel execution.
...
...                 **ONE-TIME SETUP APPROACH:**
...                 Suite Setup executes 'Setup Schedule For Week 0 and 1 wrapped with 'Run Only Once' from pabot.PabotLib.
...                 This ensures schedule setup runs exactly ONCE across all parallel processes before any tests execute.
...
...                 **PARALLEL EXECUTION ENABLED:**
...                 Tests can be executed in parallel using pabot. The setup runs once, then all tests execute concurrently.
...
...                 **TEST CASES INCLUDED:**
...                 Week 0 tests (SM1_STORE2):
...                 - BATTC00139: Verify Week In Progress Schedule Copy Generated By Servlet For Distribution List
...                 - BATTC00143: Verify The Shifts Are Unallocated And Moved To Open Pool After Transfer
...                 - BATTC00144: Verify The Shifts Are Unallocated And Moved To Open Pool After Termination
...                 Week 1 tests (SM1_STORE2):
...                 - BATTC00119: Verify Approval Of Extra Work Shift Response
...                 - BATTC00118: Verify Approval Of Open Shift Response On Web
...                 - BATTC00120: Verify Advertised Shift Response Approval
...                 - BATTC00121: Verify Approval Of Individual Swap Shift Response In Web
...                 - BATTC00186: Verify Approval Of All Eligible Swap Shift Response In Web
...                 - BATTC00193: Verify user is able to do shift trading for new hires
...                 Week 2 tests (SM1_STORE2):
...                 - BATTC00136: Verify User Is Able To Publish Schedule By Running The Servlet For Specific Unit
...                 Weeks 0-2 Navigation (SM1_STORE2):
...                 - BATTC00020: WFM-19-1 Verify Week Navigation For Schedule Page And Review Legends
...                 - BATTC00021: WFM-19-2 Verify Week Navigator On Labor Forecast Page
...                 - BATTC00022: WFM-19-3 Verify Week Navigator On Driver Forecast Page
...
...                 **EXECUTION COMMANDS:**
...
...                 Sequential execution:
...                 uv run python executor.py tests/web/l2_suite/schedule_dependent/week0_week1_week2_sm1store2_schedule_suite.robot --test-env QA28_B0
...
...                 Parallel execution (recommended, 4 processes):
...                 uv run python executor.py tests/web/l2_suite/schedule_dependent/week0_week1_week2_sm1store2_schedule_suite.robot --test-env QA28_B0 --processes 4
...
...                 With browser visible (for debugging):
...                 uv run python executor.py tests/web/l2_suite/schedule_dependent/week0_week1_week2_sm1store2_schedule_suite.robot --test-env QA28_B0 --show-browser
...
...                 **LOCK FILE CLEANUP:**
...                 If setup appears to be skipped, clean pabot lock files before running:
...                 Remove-Item -Path ".pabot_results" -Recurse -Force -ErrorAction SilentlyContinue
...
...                 **ORIGINAL TEST FILES:**
...                 Original individual test files remain in their locations for backward compatibility.
...                 After full validation, they can be deprecated/removed.

Library             pabot.PabotLib
Resource            resources/web/authentication/login.resource
Resource            resources/common/schedule_setup/common_schedule_setup.resource
Resource            resources/web/organization/organization_distribution_list.resource
Resource            resources/web/ess/shift_trade_board.resource
Resource            resources/web/rws/admin/rws_upload_api.resource
Resource            resources/web/rws/schedule/plan_status.resource
Resource            resources/web/rws/schedule/week_schedule.resource
Resource            resources/web/rws/admin/rws_upload.resource
Variables           resources/web/rws/schedule/week_schedule_page.py
Library             test_data/TestDataLibrary.py
Resource            resources/web/rws/labor_forecast/labor_forecast.resource
Resource            resources/web/rws/driver_forecast/driver_forecast.resource

Suite Setup         Run Keywords    Run Only Once    Pre Setup Schedule For Week 0 SM1Store2
...                     AND
...                     Run Only Once    Pre Setup Schedule For Week 1 SM1Store2
...                     AND
...                     Run Only Once    Pre Setup Schedule For Week 2 SM1Store2
Suite Teardown      Run Keywords    Run Only Once    Teardown Dynamic Employees For SM1Store2
...                     AND
...                     Log    Week 1 & 2 SM1_STORE2 Suite Complete - All tests executed    level=INFO
Test Teardown       Close Browser

Test Tags           week0_week1_sm1store2    bat_phase2    schedule_dependent


*** Test Cases ***
BATTC00139: Verify week in progress copy of schedule is generated by running the servlet for distribution list
    [Documentation]    Verify Week In Progress schedule copy is generated via servlet for the distribution list and visible on the Week Schedule page.
    [Tags]    battc00139    config:rws    config:weekplan_and_schedule_gen    dev:moiz    checkschedulesetup
    [Setup]    Create Distribution List For Store2
    ${store_data}    Get Store Data    template_name=model_store2
    ${distribution_list_data}    Get Distribution List Data
    Generate Week In Progress Copy With Store Distribution Using Servlet On Web    SM1_STORE2
    ...    ${store_data}[store_id]${distribution_list_data}[name]
    # Wait for WIP copy to be generated and available instead of using Sleep
    Wait Until Keyword Succeeds    ${LONG_TIMEOUT}    5s
    ...    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    ${wip_visible}    Verify Week In Progress Copy Exists On Week Schedule Page On Web
    Should Be True    ${wip_visible}    Week In Progress copy was not found on Week Schedule page.

BATTC00119: Verify approval of extra work shift response in web
    [Documentation]
    ...    Tests the complete workflow for extra work shift request, response, and approval.
    ...    Workflow: ESS6_STORE2 raises extra work request → ESS5_STORE2 responds/offers → SM1_STORE2 approves
    ...    Validates: Request creation, response acceptance, notification messages, approval operations
    ...
    ...    Preconditions (Setup via "Setup Schedule For Week template_name=1_0_sm1_store2"):
    ...    - ESS6_STORE2: Has shifts on Day 1, 2, 3. Day 4 is free (available for extra work request).
    ...    - ESS5_STORE2: Has shifts on Day 2, 3. Day 1, 4, 7 are free (can respond to extra work).
    ...    - Schedule is published for current week + 1 (week 1_0)
    ...
    ...    Test Data:
    ...    - Trading Week: Current Week +1 (1_0)
    ...    - Trading Day: Day 4 (1_3)
    ...    - Shift Start Time: 01:00
    ...    - Shift End Time: 23:00
    ...    - Preferred Shift Length: 8:00 Hours
    ...    - Requestor Notes: "Test Additional Work"
    ...
    ...    Test Steps:
    ...    1. ESS6_STORE2 logs in, navigates to shift trade page, raises extra work request for Day 4, logs out
    ...    2. ESS5_STORE2 logs in, navigates to shift trade page, responds to extra work request, logs out
    ...    3. SM1_STORE2 logs in, navigates to schedule page, verifies and approves the response, logs out
    ...    Week: 1, Store: 2
    [Tags]    battc00119    dev:amol    config:weekplan_and_schedule_gen    config:ess_shift_bidding    config:ess
    ...    config:extra_work_shift_enabled    config:auto_approve_extra_work_shift:n    om_hr    checkschedulesetup

    ${extra_work_data}    Get Extra Work Shift Data    planning_week_date=1_0    week_trade_day=1_3
    ...    extra_work_shift_length=9:00    extra_work_request_notes=Test Additional Work
    ...    extra_work_response_notes=Responding to extra work request
    Log    Extra work shift data: ${extra_work_data}

    # Step 1: ESS6_STORE2 raises extra work request for Day 4
    Login And Launch WFM Web App    user_key=ESS6_STORE2
    Navigate To ESS Shift Trade Board Page On Web
    Select Week Number On Shift Trade Board Calendar Page On Web    ${extra_work_data}[planning_week_date]
    Verify Schedule Is Published On Shift Trade Board Page On Web
    Raise Extra Work Request At Day On Shift Trade Board Page On Web    ${extra_work_data}
    ...    ${extra_work_data}[week_trade_day]
    Close Browser

    # Step 2: ESS5_STORE2 responds to/offers for the extra work request
    Login And Launch WFM Web App    user_key=ESS5_STORE2
    Navigate To ESS Shift Trade Board Page On Web
    Select Week Number On Shift Trade Board Calendar Page On Web    ${extra_work_data}[planning_week_date]
    ${requester_user}    Get User    user_key=ESS6_STORE2
    VAR    ${requester_name}    ${requester_user}[displayName]
    Respond To Additional Work Request On Shift Trade Board Page On Web
    ...    ${extra_work_data}[week_trade_day]
    ...    ${requester_name}
    ...    ${extra_work_data}[extra_work_response_notes]
    Close Browser

    # Step 3: SM1_STORE2 verifies and approves the extra work response
    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    ${extra_work_data}[planning_week_date]
    Wait Until Page Is Loaded
    ${is_schedule_published}    Check If Schedule Is In Published State On Web
    Skip If    not ${is_schedule_published}    Schedule is not Published for Current + 1 week - cannot proceed with test.
    ${requester_user}    Get User    user_key=ESS6_STORE2
    VAR    ${requester_name}    ${requester_user}[displayName]
    Approve Extra Work Request Of Associate In SM Week Schedule
    ...    ${requester_name}
    ...    ${extra_work_data}[week_trade_day]

BATTC00118: Verify approval of open shift response in web
    [Documentation]
    ...    Tests the complete workflow for responding to an open shift request for a future week.
    ...    Workflow: ESS user responds to open shift → SM approves the response → Open shift is assigned to ESS user
    ...    Validates: Open shift availability, response acceptance, notification messages, approval operations
    [Tags]    battc00118    dev:azar    config:weekplan_and_schedule_gen    config:ess_shift_bidding    config:ess
    ...    config:auto_approve_open_shift:n    om_hr
    Login And Launch WFM Web App    user_key=ESS5_STORE2
    ${open_shift_data}    Get Open Shift Data    planning_week_date=1_0    week_trade_day=1_6
    ...    respond_note=Automation Respond Note for Open Shift Approval    shift_start_time=08:00    shift_end_time=16:00
    Log    Open shift data: ${open_shift_data}
    Navigate To ESS Shift Trade Board Page On Web
    Select Week Number On Shift Trade Board Calendar Page On Web    ${open_shift_data}[planning_week_date]
    Verify Schedule Is Published On Shift Trade Board Page On Web
    ${open_shift_available}    ${shift_start}    ${shift_end}    Check If Open Shift Available For Day On Shift Trade Board Page On Web
    ...    ${open_shift_data}[week_trade_day]
    IF    ${open_shift_available}
        Respond To Open Shift Request On Shift Trade Board Page On Web    ${shift_start}    ${shift_end}
        ...    ${open_shift_data}[respond_note]    ${open_shift_data}[week_trade_day]
    END
    Close Browser
    Login To SM And Go To Selected Week Schedule Page On Web    SM1_STORE2
    ...    ${open_shift_data}[planning_week_date]
    ${ess_user}    Get User    user_key=ESS5_STORE2
    VAR    ${responder_name}    ${ess_user}[displayName]

    # Approve the open shift response (keyword handles time conversion internally)
    Approve Open Shift Response In SM Week Schedule On Web
    ...    ${open_shift_data}[week_trade_day]
    ...    ${shift_start}
    ...    ${shift_end}
    # Convert times to 24hr format for verification
    ${shift_start_24hr}    Convert UI Time Format To 24 Hour Format For Web    ${shift_start}
    ${shift_end_24hr}    Convert UI Time Format To 24 Hour Format For Web    ${shift_end}
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    ${open_shift_data}[planning_week_date]
    Go To Schedule Page On Web
    Verify Shift Exists For Associate On Specific Day On Week Schedule Page On Web
    ...    ${responder_name}
    ...    ${open_shift_data}[week_trade_day]
    ...    ${shift_start_24hr}
    ...    ${shift_end_24hr}

BATTC00120: Verify approval of advertised shift response in web
    [Documentation]    Verify SM user can approve a responded advertised shift request.
    [Tags]    battc00120    dev:moiz    config:advertised_shift_enabled    config:weekplan_and_schedule_gen    config:ess_shift_bidding
    ...    config:ess    config:auto_approve_advertise_shift:n    om_hr
    ${ess_user6}    Get User    user_key=ESS6_STORE2
    ${ess_user5}    Get User    user_key=ESS5_STORE2
    ${advertise_shift_data}    Get Advertise Shift Data    planning_week_date=1_0
    ...    notes=Automation Notes for Shift Advertise Approval    respond_note=Automation Respond Note for Shift Advertise Approval
    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    Navigate To Next Week Schedule On Web
    ${is_published}    Check If Schedule Is In Published State On Web
    Skip If    not ${is_published}    Schedule is not Published for Current + 1 week - cannot proceed with Advertise Shift test.
    Close Browser
    Login And Launch WFM Web App    user_key=ESS6_STORE2
    Navigate To ESS Shift Trade Board Page On Web
    Select Week Number On Shift Trade Board Calendar Page On Web    ${advertise_shift_data}[planning_week_date]
    Verify Schedule Is Published On Shift Trade Board Page On Web
    ${is_note_window_available}    Advertise The Shift At Day On Shift Trade Board Page On Web    ${advertise_shift_data}[planning_week_date]
    ...    ${advertise_shift_data}[notes]
    Close Browser
    Login To ESS And Go To Selected Week Shift Trade Board Of Responder On Web    ESS5_STORE2
    ...    ${advertise_shift_data}[planning_week_date]
    Respond To Advertise Request On Shift Trade Board Page On Web    ${advertise_shift_data}[planning_week_date]
    ...    ${ess_user6}[displayName]    ${advertise_shift_data}[respond_note]
    Close Browser
    Login To SM And Go To Selected Week Schedule Page On Web    SM1_STORE2    ${advertise_shift_data}[planning_week_date]
    IF    ${is_note_window_available}
        Verify Advertised Shift Response On Week Schedule Page On Web    ${ess_user6}[displayName]
    ...    ${advertise_shift_data}[planning_week_date]    ${ess_user5}[displayName]    ${advertise_shift_data}[respond_note]
    ELSE
        Verify Advertised Shift Response On Week Schedule Page On Web    ${ess_user6}[displayName]
    ...    ${advertise_shift_data}[planning_week_date]    ${ess_user5}[displayName]
    END
    Approve Advertised Shift Response On Week Schedule Page On Web    ${ess_user6}[displayName]
    ...    ${advertise_shift_data}[planning_week_date]
    Verify Shift Not Exists For Associate On Specific Day On Week Schedule Page On Web    ${ess_user6}[displayName]
    ...    ${advertise_shift_data}[planning_week_date]
    Verify Shift Exists For Associate On Specific Day On Week Schedule Page On Web    ${ess_user5}[displayName]
    ...    ${advertise_shift_data}[planning_week_date]

BATTC00121: Verify approval of individual swap shift response in web
    [Documentation]
    ...    This test verifies that an individual swap shift request can be successfully approved in the ESS Shift Trade Board workflow.
    ...    The scenario covers:
    ...    1. ESS1 creates a swap shift request to ESS2.
    ...    2. ESS2 responds and accepts the swap request.
    ...    3. The Store Manager (SM) approves the swap.
    ...    The test ensures that all notifications and approvals are correctly processed at each step.
    [Tags]    dev:komal    battc00121    config:swap_shift_enabled    config:weekplan_and_schedule_gen    config:ess_shift_bidding
    ...    config:ess    config:auto_approve_swap_shift:n    om_hr
    Login And Launch WFM Web App    user_key=ESS6_STORE2
    Navigate To ESS Shift Trade Board Page On Web
    ${shift_trade_data}    Get Individual Swap Shift Data    planning_week_date=1_0    week_trade_day=1_1
    Select Week Number On Shift Trade Board Calendar Page On Web    ${shift_trade_data}[planning_week_date]
    Verify Schedule Is Published On Shift Trade Board Page On Web
    ${ess_user2}    Get User    user_key=ESS5_STORE2
    VAR    ${responder_name}    ${ess_user2}[displayName]
    Swap The Shift At Day For Associate On Shift Trade Board Page On Web    ${shift_trade_data}[week_trade_day]    ${responder_name}
    ...    ${shift_trade_data}[swap_request_notes]
    Close Browser
    Login To ESS And Go To Selected Week Shift Trade Board Of Responder On Web    ESS5_STORE2    ${shift_trade_data}[planning_week_date]
    ${ess_user1}    Get User    user_key=ESS6_STORE2
    VAR    ${requester_name}    ${ess_user1}[displayName]
    Respond To Swap Request On Shift Trade Board Page On Web    ${shift_trade_data}[week_trade_day]    ${requester_name}
    ...    ${shift_trade_data}[swap_response_notes]
    Close Browser
    Login To SM And Go To Selected Week Schedule Page On Web    SM1_STORE2    ${shift_trade_data}[planning_week_date]
    Approve Swap Shift Request In SM Week Schedule On Web    ${requester_name}    ${responder_name}    ${shift_trade_data}[week_trade_day]

BATTC00186: Verify approval of all eligible swap shift response in web
    [Documentation]
    ...    Tests the complete workflow for responding to a swap shift request for a future week.
    ...    Workflow: Create swap request → Respond to request → Approve request
    ...    Validates: Request creation, response acceptance, notification messages, approval operations
    [Tags]    dev:komal    battc00186    config:swap_shift_enabled    config:weekplan_and_schedule_gen    config:ess_shift_bidding
    ...    config:ess    config:auto_approve_swap_shift:n    om_hr
    Login And Launch WFM Web App    user_key=ESS6_STORE2
    ${shift_trade_data}    Get All Eligible Swap Shift Data    planning_week_date=1_0    week_trade_day=1_2
    Log    Default shift data: ${shift_trade_data}
    Navigate To ESS Shift Trade Board Page On Web
    Select Week Number On Shift Trade Board Calendar Page On Web    ${shift_trade_data}[planning_week_date]
    Verify Schedule Is Published On Shift Trade Board Page On Web
    Swap Shift At Day On Shift Trade Board Page On Web    ${shift_trade_data}    ${shift_trade_data}[week_trade_day]
    ...    ${shift_trade_data}[swap_request_notes]
    Close Browser
    Login To ESS And Go To Selected Week Shift Trade Board Of Responder On Web    ESS5_STORE2
    ...    ${shift_trade_data}[planning_week_date]
    ${ess_user1}    Get User    user_key=ESS6_STORE2
    VAR    ${requester_name}    ${ess_user1}[displayName]
    ${ess_user2}    Get User    user_key=ESS5_STORE2
    VAR    ${responder_name}    ${ess_user2}[displayName]
    Respond To Swap Request On Shift Trade Board Page On Web    ${shift_trade_data}[week_trade_day]    ${requester_name}
    ...    ${shift_trade_data}[swap_response_notes]
    Close Browser
    Login To SM And Go To Selected Week Schedule Page On Web    SM1_STORE2
    ...    ${shift_trade_data}[planning_week_date]
    Approve Swap Shift Request In SM Week Schedule On Web    ${requester_name}    ${responder_name}    ${shift_trade_data}[week_trade_day]

BATTC00143: Verify the shifts are unallocated and moved to open pool after transfer
    [Documentation]
    ...    This test case verifies that when an associate is transferred to another store,
    ...    their assigned shifts in the original store are unallocated and moved to the open shift pool.
    ...
    ...    **Test Flow:**
    ...    1. Verify associate has shifts in current week (today) and next week (JIRA days 1,2,4,6,7 = Framework days 0,1,3,5,6) in STORE2
    ...    2. Import HRCI store transfer data (transfer from STORE2 to STORE1, effective Day 1 of next week)
    ...    3. Verify associate still has shift for today in STORE2 (before transfer effective date)
    ...    4. Verify associate is no longer visible in STORE2 for next week
    ...    5. Verify shifts for next week are moved to open shift pool in STORE2
    [Tags]    dev:azar    battc00143    config:rws    config:weekplan_and_schedule_gen    config:allow_shift_move_operation    new_hire
    ${ess_user_nh4}    Get Dynamic Employee    ESSNH4_STORE2
    VAR    ${associate_display_name}    ${ess_user_nh4}[displayName]
    ${schedule_data_week}    Get Shift Time Pattern Data    template_name=morning_7hr
    ${shift_start_time_week}    Convert UI Time Format To 24 Hour Format For Web    ${schedule_data_week['uiStartTime']}
    ${shift_end_time_week}    Convert UI Time Format To 24 Hour Format For Web    ${schedule_data_week['uiEndTime']}
    ${shift_data}    Get Employee Shift Setup Data    template_name=add01356_standard7
    ${current_week_day_offset}    Get Current Week Day Offset
    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    0_0
    Verify Shift Exists For Associate On Specific Day On Week Schedule Page On Web    ${associate_display_name}
    ...    ${current_week_day_offset}    ${shift_start_time_week}    ${shift_end_time_week}
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    1_0
    Verify Shift Exists For Associate On Multiple Days On Week Schedule Page On Web    ${associate_display_name}
    ...    ${shift_data}    1_0    ${shift_start_time_week}    ${shift_end_time_week}    True
    Log Out From Web Application
    Close Browser
    Log    Starting HRCI import for associate store transfer    level=INFO
    Transfer ESSNH4 STORE2 Employee Via HRCI For Store On Web
    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    0_0
    Verify Shift Exists For Associate On Specific Day On Week Schedule Page On Web    ${associate_display_name}
    ...    ${current_week_day_offset}    ${shift_start_time_week}    ${shift_end_time_week}
    Select Week Number On Week Schedule Page On Web    1_0
    Verify Shift Not Exists For Associate On Multiple Days On Week Schedule Page On Web    ${associate_display_name}
    ...    ${shift_data}    1    ${shift_start_time_week}    ${shift_end_time_week}
    Verify Open Shifts Exist For Multiple Days On Week Schedule Page On Web    ${shift_data}    ${shift_start_time_week}
    ...    ${shift_end_time_week}
    Log Out From Web Application

BATTC00144: Verify the shifts are unallocated and moved to open pool after termination
    [Documentation]
    ...    This test case verifies that when an associate is terminated,
    ...    their assigned shifts are unallocated and moved to the open shift pool.
    [Tags]    dev:komal    battc00144    config:rws    new_hire    config:weekplan_and_schedule_gen    config:allow_shift_move_operation

    ${ess_user_nh6}    Get Dynamic Employee    ESSNH6_STORE2
    VAR    ${associate_display_name}    ${ess_user_nh6}[displayName]
    ${schedule_data_week}    Get Shift Time Pattern Data    template_name=morning_7hr
    # Convert UI formatted times back to 24-hour format for verification keywords
    ${shift_start_time_week}    Convert UI Time Format To 24 Hour Format For Web    ${schedule_data_week['uiStartTime']}
    ${shift_end_time_week}    Convert UI Time Format To 24 Hour Format For Web    ${schedule_data_week['uiEndTime']}
    ${shift_data}    Get Employee Shift Setup Data    template_name=add01356_standard7
    ${current_week_day_offset}    Get Current Week Day Offset
    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    0_0
    Verify Shift Exists For Associate On Specific Day On Week Schedule Page On Web    ${associate_display_name}
    ...    ${current_week_day_offset}    ${shift_start_time_week}    ${shift_end_time_week}
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    1_0
    Verify Shift Exists For Associate On Multiple Days On Week Schedule Page On Web    ${associate_display_name}
    ...    ${shift_data}    1_0    ${shift_start_time_week}    ${shift_end_time_week}    True
    Log Out From Web Application
    Close Browser

    # Import HRCI data for associate termination
    Log    Starting HRCI import for associate termination    level=INFO
    Terminate ESSNH6 Employee For HRCI Test

    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    0_0
    Verify Shift Exists For Associate On Specific Day On Week Schedule Page On Web    ${associate_display_name}
    ...    ${current_week_day_offset}    ${shift_start_time_week}    ${shift_end_time_week}
    Select Week Number On Week Schedule Page On Web    1_0
    Verify Associate Is Terminated On Week Schedule Page On Web    ${associate_display_name}
    Verify Open Shifts Exist For Multiple Days On Week Schedule Page On Web    ${shift_data}    ${shift_start_time_week}
    ...    ${shift_end_time_week}
    Log Out From Web Application

BATTC00193: Verify user is able to do shift trading for new hires
    [Documentation]    Verifies that a new hire user can successfully advertise a shift and then withdraw the advertised shift.
    [Tags]    config:ess_shift_bidding    config:ess    action:write    battc00193    dev:komal    new_hire_azar    om_hr
    ...    config:weekplan_and_schedule_gen    config:advertised_shift_enabled
    Skip If Today Is Last Day Of Week
    Login And Launch WFM Web App    ESSNH1_STORE2    is_dynamic_user=True
    ${advertise_shift_data}    Get Advertise Shift Data    template_name=withdraw_shift
    Navigate To ESS Shift Trade Board Page On Web
    Select Week Number On Shift Trade Board Calendar Page On Web    ${advertise_shift_data}[planning_week_date]
    Verify Schedule Is Published On Shift Trade Board Page On Web
    Advertise The Shift At Day On Shift Trade Board Page On Web    ${advertise_shift_data}[week_trade_day]
    ...    ${advertise_shift_data}[notes]
    Withdraw Advertised Shift On Shift Trade Board Page On Web    ${advertise_shift_data}[week_trade_day]

BATTC00136: Verify User Is Able To Publish Schedule By Running The Servlet For Specific Unit
    [Documentation]    Verify user is able to publish schedule by running the servlet for specific unit
    ...    Week: 2
    # [Tags]    dev:bushra    action:write    config:rws    battc00136    config:weekplan_and_schedule_gen
    [Tags]    obsolete    # This scenario is covered in suite setup itself and does not need to be a separate test case.
    #    Keeping the test case for reference until suite setup is fully validated.
    Login And Launch WFM Web App    user_key=SM1_STORE2
    ${schedule_data}    Get Schedule Generation Setup Data    template_name=2_0_sm1_store2
    ${store_data}    Get Store Data    template_name=model_store2
    Navigate To RWS Schedule Week Schedule Page On Web
    Select Week Number On Week Schedule Page On Web    ${schedule_data}[week_start_date]
    Go To Schedule Page On Web
    ${unpublished}    Check If Schedule Generated And In Unpublished State On Web
    IF    not ${unpublished}
        Skip    Schedule is not in Unpublished state before running servlet. Please check schedule setup execution for week 2.
    END
    Check And Lock Schedule Via API For Week Start Date On Web    ${schedule_data}
    Publish Week Schedule With Unit Id Using Servlet On Web    ${schedule_data}[store_manager_user_key]
    ...    ${schedule_data}[week_start_date]    ${store_data}[unit_skey]
    Check And Wait Till Schedule Is In Published State On Web    ${schedule_data}[week_start_date]

# ==============================================================================
# WEEKS 0–2 NAVIGATION — SM1_STORE2
# ==============================================================================

BATTC00020: Verify week navigation for schedule page and review legends
    [Documentation]
    ...    Verify week navigator functionality on week schedule page and review legends.
    ...    If schedule is in plan status, the test is skipped.
    [Tags]    dev:amol    action:read    battc00020    config:rws    config:weekplan_and_schedule_gen    checkschedulesetup

    VAR    ${number_of_weeks_to_navigate}    2

    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Schedule Week Schedule Page On Web

    ${is_in_plan_status}    Check If Schedule Is In Plan Status On Web
    IF    ${is_in_plan_status}
        Log    Schedule is in plan status; skipping week navigation and legend verification.
        SKIP    Test skipped because schedule is in plan status.
    ELSE
        Click On Legend Icon And Verify All Tabs
        Log    Schedule is not in plan status; proceeding with week navigation verification.
        Verify Week Navigation On Week Schedule Page On Web    ${number_of_weeks_to_navigate}
    END
    Log Out From Web Application

BATTC00021: Verify week navigation for labor forecast page
    [Documentation]    Verify week navigator functionality on labor forecast page
    [Tags]    dev:amol    action:read    battc00021    config:rws    config:weekplan_and_schedule_gen    module:forecast

    VAR    ${number_of_weeks_to_navigate}    2

    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Labor Forecast Page On Web
    Verify Week Navigation On Labor Forecast Page On Web    ${number_of_weeks_to_navigate}
    Log Out From Web Application

BATTC00022: Verify week navigation for driver forecast page
    [Documentation]    Verify week navigator functionality on driver forecast page
    [Tags]    dev:amol    action:read    battc00022    config:rws    config:weekplan_and_schedule_gen    config:legacy_forecasting
    ...    module:forecast

    VAR    ${number_of_weeks_to_navigate}    2

    Login And Launch WFM Web App    user_key=SM1_STORE2
    Navigate To RWS Driver Forecast Forecast Page On Web
    Verify Week Navigation On Driver Forecast Page On Web    ${number_of_weeks_to_navigate}
    Log Out From Web Application


*** Keywords ***
Create Distribution List For Store2
    [Documentation]    Creates the distribution list for Store 2.
    Login And Launch WFM Web App    user_key=SYSADMIN
    Navigate To RWS Organization Distribution List Page On Web
    Verify RWS Distribution List Page Loaded On Web
    ${store_data}    Get Store Data    template_name=model_store2
    ${distribution_list_data}    Get Distribution List Data
    ${distribution_list_exists}    Check If Distribution List Exists On Distribution List Page On Web
    ...    ${store_data}[store_id]${distribution_list_data}[name]
    IF    not ${distribution_list_exists}
        ${dl_name}    ${dl_description}    Add New Distribution List From Distribution List Maintenance Page On Web    ${store_data}
        ...    ${distribution_list_data}
        Log    Distribution list added with name: ${dl_name} and description: ${dl_description}
        Add Unit Selection Criteria Based On Criterion Type On Web    ${distribution_list_data}[criterion_type]
        ...    ${distribution_list_data}[criterion]    ${store_data}[store_name]
        Log    Unit selection criteria added for distribution list: ${dl_name} with store: ${store_data}[store_name]
    END
    Close Browser

Transfer ESSNH4 STORE2 Employee Via HRCI For Store On Web
    [Documentation]    Transfers the dynamic employee ESSNH4_STORE2 from STORE2 to STORE1 via HRCI file upload
    ...
    ...    This performs store transfer via HRCI with effective date as Day 1 of Current Week + 1.
    ...    The employee is transferred from STORE2 to STORE1.

    Log    🔄 Transferring ESSNH4_STORE2 from STORE2 to STORE1 via HRCI...    level=INFO

    # Get employee from suite variable
    ${essnh4_store2}    Get Dynamic Employee    ESSNH4_STORE2

    # Get store data for STORE1 (destination)
    ${store1_data}    Get Store Data

    # Get date configuration from environment
    ${date_format}    Get Config Value    SERVER_DF
    # Calculate transfer effective date as Day 1 of Current Week + 1 (1_0)
    ${transfer_effective_date}    Calculate Date From Week Day Offset    1_0    date_format=${date_format}
    # Calculate end date as Day 1 of Current Week + 2 (2_0)
    ${transfer_end_date}    Calculate Date From Week Day Offset    2_0    date_format=${date_format}

    # Get organizational data from STORE1
    ${staff_group_id}    Get System Value    HRBAStaffGroupId    NEWHIRE_STORE2_SG_1
    ${department_id}    Get System Value    HRBADepartmentId    NEWHIRE_STORE2_DEPT_1

    # Create HRCI store transfer data using default template with field overrides
    ${hrci_transfer_data}    Get Hrci Store Transfer Data
    ...    employee_id=${essnh4_store2}[employee_id]
    ...    effective_date=${transfer_effective_date}
    ...    end_date=${transfer_end_date}
    ...    home_store_id=${store1_data}[store_id]
    ...    home_department_id=${department_id}
    ...    home_staff_group_id=${staff_group_id}

    # Define file path for HRCI transfer file
    VAR    ${hrci_file_path}    web/Generated/HRCI_Store_Transfer_ESSNH4.txt

    # Login as SYSADMIN and upload HRCI file
    Login And Launch WFM Web App    user_key=SYSADMIN
    Perform HRCI Store Transfer Upload On Web    ${hrci_file_path}    ${hrci_transfer_data}
    Close Browser

    Log    ✅ Successfully transferred ESSNH4_STORE2 from STORE2 to STORE1, effective ${transfer_effective_date}    level=INFO

Terminate ESSNH6 Employee For HRCI Test
    [Documentation]    Terminates the ESSNH6_STORE2 dynamic employee via HRCI API as part of test execution.
    ...
    ...    This keyword is used as a test step in BATTC00144 to simulate employee termination
    ...    and verify that shifts are unallocated and moved to the open pool after termination.
    ...    The termination occurs mid-test to test the business logic, not as a cleanup operation.

    Log    🔄 Test Step: Terminating dynamic employee via HRCI API to test business logic...    level=INFO

    # Get date configuration from environment (not hardcoded!)
    ${date_format}    Get Config Value    SERVER_DF
    # Calculate termination date as the last day of the current week (7th day)
    ${termination_date}    Calculate Date From Week Day Offset    0_6    date_format=${date_format}

    # Get employee from suite variable
    ${essnh6_store2}    Get Dynamic Employee    ESSNH6_STORE2

    # Create HRCI record for termination
    ${hrci_essnh6_store2}    Get Hrci Api Upload Data
    ...    employee_id=${essnh6_store2}[employee_id]
    ...    effective_date=${termination_date}

    VAR    @{records}    ${hrci_essnh6_store2}
    Update HRCI User Status Via API
    ...    user_key=SYSADMIN
    ...    records_data=${records}

    Log    ✅ Successfully terminated ESSNH6_STORE2: Employee ID=${essnh6_store2}[employee_id]    level=INFO
    Log    🔄 Employee termination test step complete    level=INFO
