loginpage_username_txt = "//input[@type='text' and @spellcheck='false']"
loginpage_password_txt = "//input[@type='password' and @placeholder]"
loginpage_login_btn = "button.login-button"
loginpage_mobile_login_btn = "//span[@class='login-big-font login-button-fix']"
loginpage_logout_btn = "button#rfxHeaderSignOutButton"
loginpage_sudo_kernel_header = "//span[normalize-space()='KERNEL']"
loginpage_sudo_loginas_menu = "a[id=LOGIN_AS]"
loginpage_sudo_username_textbox = "input[id=userId]"
loginpage_sudo_loginas_button = '//button[normalize-space()="Login As"]'
loginpage_sudo_loginas_link = "div[id=loginAsLinkContainer] span"
loginpage_mywork_landing_page = "//div[@class='my-work notification-detail']"
reset_password_page_container = "//div[@id='resetPasswordContainer']"
loginpage_laug_icon = "//a[@id='methodVarFun']"
loginpage_Eng_US = "//span[normalize-space()='English (United States)']"
loginpage_locale_option="//span[@id='change#{locale}']"
loginpage_after_logout_username_txtbox = "//input[@type='text' and @spellcheck='false']"
loginpage_login_authentication_error_msg = "//td[@id='invalidUserCredentials']"
loginpage_nonmywork_landing_page = "//div[@id='mainContainer']"
