PERIOD_PAYROLL_RELEASE_PAGE_YEAR_DROPDOWN = "//select[@ng-model='prCtrl.selectedYear']"
PERIOD_PAYROLL_RELEASE_PAGE_MONTH_DROPDOWN = "//select[@ng-model='prCtrl.selectedMonth']"
PERIOD_PAYROLL_RELEASE_PAGE_QUARTER_DROPDOWN = "//select[@ng-model='prCtrl.selectedQuarter']"
PERIOD_PAYROLL_RELEASE_PAGE_WEEK_DROPDOWN = "//select[@ng-model='prCtrl.selectedWeek']"
PERIOD_PAYROLL_RELEASE_PAGE_FILTER_BUTTON = "//img[@id='filterImg'][@class='toggle-filter']"
PERIOD_PAYROLL_RELEASE_PAGE_FILTER_APPLY_BUTTON = "//input[@value='Apply']"
PERIOD_PAYROLL_RELEASE_PAGE_RELEASES_STATUS_VALUE = "(//tr[contains(@class,'aggregateRow')]//td[contains(@ng-if,'row.releaseStatus')])[1]"
PERIOD_PAYROLL_RELEASE_PAGE_REOPEN_ACTION = "//a[contains(@ng-click,'reOpen')]"
PERIOD_PAYROLL_RELEASE_PAGE_RELEASE_ACTION = "//a[contains(@ng-click,'releasePayroll')]"
PERIOD_PAYROLL_RELEASE_PAGE_REOPEN_ACTION_FOR_PERIOD = "//td[@class='nameContainer ng-binding' and contains(text(),'{PERIOD}')]//parent::tr/td/a[contains(@ng-click,'reOpen')]"
PERIOD_PAYROLL_RELEASE_PAGE_RELEASE_ACTION_FOR_PERIOD = "//td[@class='nameContainer ng-binding' and contains(text(),'{PERIOD}')]//parent::tr/td/a[contains(@ng-click,'releasePayroll')]"
PERIOD_PAYROLL_RELEASE_PAGE_PERIOD_STATUS_VALUE = "(//td[@class='nameContainer ng-binding' and contains(text(),'{PERIOD}')]//parent::tr/td[contains(@ng-if,'row.releaseStatus')])[1]"
PERIOD_PAYROLL_RELEASE_PAGE_SPINNER = "//div[contains(@class,'overlay')]//following-sibling::div[contains(@class,'rfx-spinner')]"
PAYROLL_REFRESH_BUTTON = "//input[@value='Refresh']"
PAYROLL_RELEASE_BUTTON_LOCATOR = "//tr[contains(@class,'aggregateRow')]//td[contains(text(),'{PAYFILE_NAME}')]/following-sibling::td//a[(text()='Release')]"
PAYROLL_RELEASE_SUCCESS_MESSAGE = "//div[contains(text(),'Period payroll release successful for - {PAYFILE_NAME}')]"
PAYROLL_RELEASE_STATUS = "//tr[contains(@class,'aggregateRow')]//td[contains(text(),'{PAYFILE_NAME}')]/following-sibling::td[text()='{EXPECTED_STATUS}']"
PERIOD_PAYROLL_RELEASE_PAGE_NOTIFICATION = "//div[@class='notifyMsg ng-binding ng-scope']"